### ISSUE TITLE
iPhone x* and 11* status bar look the same

### ISSUE THREAD

**Issue by DarkPlayerr** [hieuvh/HalFiPad#6]
Self explanatory. iphone se1 on ios 14.1 with checkrain
![image](https://user-images.githubusercontent.com/22507352/105646127-707cc180-5e9e-11eb-93d5-1f860a6eb3eb.png)
![image](https://user-images.githubusercontent.com/22507352/105646132-75417580-5e9e-11eb-9cff-82700ad5fd1f.png)

**Comment by hieuvh** [comment]
should remove it because it crashes on iOS 14 and I make it look the same to fix this.

**Comment by DarkPlayerr** [comment]
oh ok
