### ISSUE TITLE
ios 14.4 iPhone 7.When I use modern mode, the notification banner is a little bit down

### ISSUE THREAD

**Issue by srcenchen** [hieuvh/HalFiPad#7]
When I use modern mode, the notification banner is a little bit down.
It is much lower than before.
I think ios thinks it's iphone x
It is so low, and has so much white space.
Please fix the little bugs.

**Comment by hieuvh** [comment]
https://github.com/hieuvh/ProGesture/releases/tag/v1.0.1

**Comment by sanenchen-hub** [comment]
[](https://feng-bbs-att-1255531212.image.myqcloud.com/2021/02/05/1531028jpxlp81hugfg2fq.jpeg?imageMogr2/format/jpg/interlace/0/quality/100)
It can't fix the bug.
you can see the screenshot

**Comment by sanenchen-hub** [comment]
https://feng-bbs-att-1255531212.image.myqcloud.com/2021/02/05/1531028jpxlp81hugfg2fq.jpeg?imageMogr2/format/jpg/interlace/0/quality/100

**Comment by hieuvh** [comment]
I know. I will fix it if I can.
